### ISSUE TITLE
AtomicUsize instead of Mutex

### ISSUE THREAD

**Issue by jnicholls** [softprops/waitgroup#4]
I think an atomic counter would be better than a Mutex around usize. It avoids a syscall at the least.

**Comment by ntimeu** [comment]
IMHO, using a mutex is a better idea than an atomic type, for several reasons :
- the Condvar put the waiting thread into sleep, so that it does not consume any CPU time (which is good when awaiting on a busy machine or long-running tasks)
- using atomic data would force waiting thread to "actively" wait, like reading the data at each loop turn
- Condvar are strongly linked with Mutex, as they lock/unlock the corresponding mutex with the MutexGuard

**Comment by jnicholls** [comment]
When I suggest removing the Mutex, that also means removing the Condvar...just to be clear. So the existence of the Condvar in and of itself is not a reason to keep the Mutex.

As to the busy wait vs. passive wait, this all depends on the workload.  Typically I yield the CPU after checking the atomic value to be friendly to other threads if there is contention.  If there is no contention, then sure the CPU will continue checking.  If the use case is a real-time system with many cores, atomic is the way to go.  Otherwise the Condvar/Mutex makes more sense.  I suppose the latter is better for the general use cases where latency is not a concern and power usage should be minimal.

**Comment by softprops** [comment]
I'm open to change. 

For some background the goal was support for something like java's countdownlatch or golang's waitgroup. I want a utility that allows one thread to await the completion of a number of async tasks. I got the condvar idea from it's [rustdoc example](https://doc.rust-lang.org/std/sync/struct.Condvar.html). This usecase seemed to fit condvar perfectly because I wanted to await the countdown condition in almost the same exact manner as the condvar doc example. 

I get that the mutexes themselves have a cost but I'm not sure what a good direction would be without one since convar depends on the mutex guard. The alternative is to have some loop in the current thread that sleeps / checks cond, sleeps / checks cond, ect. If that's the recommended approach I'm not super clear on what condvars plus their dependency on mutexes _should_ be used for. I can go either way but I really appreciate both points of view and am open to suggestions.
